version: '2.1'

services:
  mariadb:
    image: registry.drycc.cc/drycc-addons/mariadb:10.8
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/drycc/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', '/opt/drycc/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mariadb_data:
    driver: local
