version: '2.1'

services:
  mariadb:
    image: registry.drycc.cc/drycc-addons/mariadb:10.8
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/drycc/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - DRYCC_DEBUG=true
      - MARIADB_ROOT_PASSWORD=rootpassoword
      - MARIADB_DATABASE=my_database
      - MARIADB_USER=master
      - MARIADB_PASSWORD=masterpassword
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=replicator
      - MARIADB_REPLICATION_PASSWORD=replicatepassword
    healthcheck:
      test: ['CMD', 'init-stack', '/opt/drycc/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mariadb_data:
    driver: local
